# Generated by Django 2.0.5 on 2018-05-31 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0002_auto_20180530_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dest',
        ),
        migrations.AddField(
            model_name='dest',
            name='user',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
