# Generated by Django 2.0.5 on 2018-05-31 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20180531_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
